src/InternationalCookies.NoAuth/Controllers/CookieController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using InternationalCookies.Data;
using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;
using System.Collections.Generic;
using InternationalCookies.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace InternationalCookies.Controllers
{

    public class CookieController : Controller
    {
        private ICookieService _cookieService;

        public CookieController(ICookieService cookieService)
        {    
            _cookieService = cookieService;          
        }

        public IActionResult Index()
        {
            return View(_cookieService.GetAllCookies());
        }

    }
}

src/InternationalCookies.NoAuth/Controllers/HomeController.cs
using InternationalCookies.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace InternationalCookies.Controllers
{
    public class HomeController : Controller
    {
        private ILogger<HomeController> _logger;
        private IHelperService _helperService;

        public HomeController(ILogger<HomeController> logger, IHelperService helperService)
        {
            _logger = logger;
            _helperService = helperService;
        }
        public IActionResult Index()
        {
            _logger.LogInformation("Barries index is hit");
            return View();
        }

        public IActionResult About()
        {      
            return View();
        }

        public IActionResult Error()
        {          
            return View();
        }

        public IActionResult ClearCache()
        {
                _helperService.ClearCache(User.Identity.Name);
            return RedirectToAction("Index");
        }
    }
}

src/InternationalCookies.NoAuth/Controllers/OrderController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using InternationalCookies.Data;
using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using InternationalCookies.Data.Interfaces;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;
using System;

namespace InternationalCookies.Controllers
{

    public class OrderController : Controller
    {
        private IOrderService _orderService;    
        private IDistributedCache _cache;
        private Guid _storeId = new Guid("2b76901f-ca39-417d-bfc3-498d0bb56e20");


        public OrderController(IOrderService orderService, IDistributedCache cache)
        {
            _orderService = orderService;      
            _cache = cache;            
        }

        public IActionResult Index()
        {
            var orders = _orderService.GetAllOrdersByStore(_storeId);            

            return View(orders);
        }


        public IActionResult Detail(int id)
        {            
             var order = _orderService.GetOrderById(id, _storeId);           

            return View(order);
        }

        public IActionResult CancelOrder(int id)
        {
            _orderService.CancelOrder(id, _storeId);            

            return RedirectToAction("Index");
        }

        public IActionResult PlaceOrder(int id)
        {
            _orderService.PlaceOrder(id, _storeId);            

            return RedirectToAction("Index");
        }

        public IActionResult AddCookieToOrderLine(int cookieId)
        {
            _orderService.AddCookieToOrder(cookieId, _storeId);            

            return RedirectToAction("Index", "Order");
        }
    }
}

src/InternationalCookies.NoAuth/Views/Cookie/Index.cshtml
@model List<Cookie>
@{
    ViewData["Title"] = "Cookies!";
}

<h2>Check out the awesome assortment of cookies:</h2>

@for (int i = 0; i < Model.Count; i++)
{
    if (i ==0)
    {
        @:<div class="row">
    }
    <form action="/Order/AddCookieToOrderLine" id="AddCookieToOrderLine@@@i">
      
        <input type="hidden" value="@Model[i].Id" name ="cookieId" id="cookieId" />
        <div class="col-md-2">
            <p>
                <strong>@Model[i].Name</strong>
            </p>
            <p>
                <img src="@Model[i].ImageUrl" alt="@Model[i].Name" width="110" height="110" />
            </p>
            <p>
                € @Model[i].Price.ToString(CultureInfo.CurrentCulture) / piece
            </p>
            <p><button type="submit" >Add to order</button></p>
        </div>
    </form>

    if (i % 2 == 0 && i > 0)
    {
        @:</div>
        @:<div class="row">
    }
}

src/InternationalCookies.NoAuth/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>About this application</h2>
<h3>This is a demo application that accompanies a <a href="https://app.pluralsight.com/library/courses/azure-paas-building-global-app/" target="_blank">Pluralsight</a> course</h3>

<p>This application is created as an example application to show how to create a web application that is used globally and hosted in Microsoft Azure.</p>
<p>You can find the code for this application on <a href="https://github.com/bmaluijb/InternationalCookies" target="_blank">GitHub.</a></p>
<p>If you have any questions about this app, contact <a href="mailto:barry@waardedoorit.nl">barry@waardedoorit.nl</a></p>

src/InternationalCookies.NoAuth/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/InternationalCookies.NoAuth/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<img src="https://intcookie.azureedge.net/cdn/cookie.jpg" alt="cookie" />

<span style="font-size:xx-large">We trade cookies all over the world!</span>


<div class="row">

    <div class="col-md-4">
        <h2>Cookies!</h2>
        <ul>
            <li>We love all cookies!</li>
            <li>Chocolate Cookie,</li>
            <li>Butter Cookie,</li>
            <li>Macaroons</li>
            <li>You name it, we love them!</li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>Register</h2>
        <ul>
            <li>Register your store to order cookies</li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>We are</h2>
        <ul>
            <li>International Cookies</li>
            <li>We send cookies to our stores</li>
            <li>All over the world</li>
            <li>In 150 countries</li>
        </ul>
    </div>
</div>

src/InternationalCookies.NoAuth/Views/Order/Detail.cshtml
@model Order
@{
    ViewData["Title"] = "Order detail";
}

@if (Model == null)
{

    <h2>No order was found.</h2>
}
else
{

    <h2>Details for order with Id @Model.Id</h2>

    <fieldset>
        <legend>Order</legend>
        Date: @Model.Date.LocalDateTime.ToString("d") <br />
        Total Price: € @Model.Price.ToString(CultureInfo.CurrentCulture) <br />
        Status: @Model.Status <br />
        @if (@Model.Id == 0)
        {
            <a href="PlaceOrder?id=@Model.Id">Place order</a><br />
        }


        <a href="CancelOrder?id=@Model.Id">Cancel order</a>

    </fieldset>

    <h3>Order lines:</h3>
    <table>
        <tr>
            <td>Cookie name</td>
            <td># cookies</td>
        </tr>
        @foreach (var line in Model.OrderLines)
        {
            <tr>
                <td>@line.Cookie.Name</td>
                <td>@line.Quantity</td>
            </tr>
        }

    </table>
}

src/InternationalCookies.NoAuth/Views/Order/Index.cshtml
@model List<Order>
@{
    ViewData["Title"] = "Orders";
}


<h2>Here are your orders:</h2>

<table>
    <tr>
        <td>Order date</td>
        <td># order lines</td>
        <td>Total price</td>
        <td>Status</td>
        <td></td>
        <td></td>

    </tr>
    @foreach (var order in Model)
    {
        <tr>
            <td>@order.Date.ToLocalTime().ToString("d")</td>
            <td>@order.OrderLines.Count</td>
            <td>€ @order.Price.ToString(CultureInfo.CurrentCulture)</td>
            <td>@order.Status</td>
            <td><a href="Order/Detail?id=@order.Id" >Details</a></td>

            <td><a href="Order/CancelOrder?id=@order.Id">Cancel order</a></td>
            @if (order.Id == 0)
            {
                <td><a href="Order/PlaceOrder?id=@order.Id">Place order</a></td>
            }
        </tr>
    }

</table>

src/InternationalCookies.NoAuth/Views/Shared/Components/Region/Default.cshtml
Environment: @ViewData["region"]   

src/InternationalCookies.NoAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternationalCookies</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">International Cookies</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Cookie" asp-action="Index">Cookies</a></li>
                    <li><a asp-area="" asp-controller="Order" asp-action="Index">Orders</a></li>
                </ul>     
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()        
        <hr />
        @await Component.InvokeAsync("Region")
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>